extern crate itertools;
mod sudoku ;

fn main() {
    {
        let g = sudoku::GridInfo {
            height: 9,
            width: 9,
            square: 3,
            values: vec!['1', '2', '3', '4', '5', '6', '7', '8', '9'],
        };
        let values = vec![
            None,
            None,
            Some('2'),
            None,
            None,
            Some('6'),
            None,
            None,
            Some('7'),
            Some('5'),
            Some('7'),
            Some('9'),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some('4'),
            None,
            Some('2'),
            Some('7'),
            None,
            Some('3'),
            None,
            None,
            Some('4'),
            None,
            None,
            Some('3'),
            Some('8'),
            Some('2'),
            None,
            None,
            Some('1'),
            Some('8'),
            Some('5'),
            None,
            Some('9'),
            None,
            Some('4'),
            None,
            Some('3'),
            Some('2'),
            Some('2'),
            None,
            None,
            Some('6'),
            Some('5'),
            Some('7'),
            None,
            None,
            Some('4'),
            None,
            None,
            Some('8'),
            None,
            Some('6'),
            Some('5'),
            None,
            Some('4'),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some('7'),
            Some('8'),
            Some('9'),
            Some('7'),
            None,
            None,
            Some('1'),
            None,
            None,
            Some('2'),
            None,
            None,
        ];
        let solution = sudoku::solve(&sudoku::Problem {
            grid: g,
            values: values,
        });
        println!("{:?}", solution);
    }
}
